### PR TITLE
fix for weird integer issue + tests

### LINKED ISSUE #225: weird int64 conversion error
The matrix is just `jl_m = [1 2 3; 4 5 6]` but somehow a very huge number appears during conversion. `W` is a polymake sparse-matrix created from `jl_m`.

something like this happened some time ago on travis, now we see this once more on github actions:
```
2020-02-19T14:19:10.7421790Z Constructors/Converts: Error During Test at /Users/runner/runners/2.165.2/work/Polymake.jl/Polymake.jl/test/sparsematrix.jl:60
2020-02-19T14:19:10.7422470Z   Test threw exception
2020-02-19T14:19:11.5055310Z   Expression: jl_m == convert(Base.Matrix{T}, W)
2020-02-19T14:19:11.5751490Z   InexactError: Int64(Int64, 14987988354931562665)
2020-02-19T14:19:11.5751760Z   Stacktrace:
2020-02-19T14:19:11.5753690Z    [1] Int64(::BigInt) at ./gmp.jl:346
2020-02-19T14:19:11.5753980Z    [2] Type at ./number.jl:7 [inlined]
2020-02-19T14:19:11.5755000Z    [3] convert at ./number.jl:7 [inlined]
2020-02-19T14:19:11.5755180Z    [4] convert(::Type{Rational{Int64}}, ::Polymake.RationalAllocated) at /Users/runner/runners/2.165.2/work/Polymake.jl/Polymake.jl/src/rationals.jl:45
2020-02-19T14:19:11.5755400Z    [5] setindex! at ./array.jl:769 [inlined]
2020-02-19T14:19:11.5755640Z    [6] copyto!(::IndexLinear, ::Array{Rational{Int64},2}, ::IndexCartesian, ::Polymake.SparseMatrixAllocated{Polymake.Rational}) at ./abstractarray.jl:742
2020-02-19T14:19:11.5755800Z    [7] copyto! at ./abstractarray.jl:723 [inlined]
2020-02-19T14:19:11.5755910Z    [8] Type at ./array.jl:497 [inlined]
2020-02-19T14:19:11.5756070Z    [9] convert(::Type{Array{Rational{Int64},2}}, ::Polymake.SparseMatrixAllocated{Polymake.Rational}) at ./array.jl:489
2020-02-19T14:19:11.5756170Z    [10] macro expansion at /Users/runner/runners/2.165.2/work/Polymake.jl/Polymake.jl/test/sparsematrix.jl:60 [inlined]
2020-02-19T14:19:11.5756310Z    [11] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
2020-02-19T14:19:11.5756460Z    [12] macro expansion at /Users/runner/runners/2.165.2/work/Polymake.jl/Polymake.jl/test/sparsematrix.jl:20 [inlined]
2020-02-19T14:19:11.5756590Z    [13] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
2020-02-19T14:19:11.5775700Z    [14] top-level scope at /Users/runner/runners/2.165.2/work/Polymake.jl/Polymake.jl/test/sparsematrix.jl:3
2020-02-19T14:20:35.8008180Z Test Summary:                   | Pass  Error  Total
2020-02-19T14:20:35.8622130Z Polymake                        | 6055      1   6056
2020-02-19T14:20:35.8627570Z   Polymake.Integer              |  103           103
2020-02-19T14:20:35.8632270Z   Polymake.Rational             |  220           220
2020-02-19T14:20:35.8638140Z   Polymake.Vector               | 1107          1107
2020-02-19T14:20:35.8644940Z   Polymake.Matrix               | 1171          1171
2020-02-19T14:20:35.8650750Z   Polymake.Set                  |  126           126
2020-02-19T14:20:35.8658190Z   julia Base.Sets compatibility |  249           249
2020-02-19T14:20:35.8663190Z   Polymake.Array                |  180           180
2020-02-19T14:20:35.8671670Z   IncidenceMatrix               |  948           948
2020-02-19T14:20:35.8676650Z   converting                    |   32            32
2020-02-19T14:20:35.8682450Z   bigobject                     |   58            58
2020-02-19T14:20:35.8689070Z   Interface functions           |   19            19
2020-02-19T14:20:35.8693420Z   Indexing helpers              |   53            53
2020-02-19T14:20:35.8699860Z   Polymake.SparseMatrix         | 1291      1   1292
2020-02-19T14:20:35.8704830Z     Constructors/Converts       |  471      1    472
2020-02-19T14:20:35.8712040Z     Low-level operations        |  247           247
2020-02-19T14:20:35.8715980Z     Arithmetic                  |  546           546
2020-02-19T14:20:35.8721430Z     findnz                      |    3             3
2020-02-19T14:20:35.8729020Z   Polymake.TropicalNumber       |  230           230
2020-02-19T14:20:35.8737670Z   Polymake.Polynomial           |  268           268
```

### PR DESCRIPTION
**Pull request by kalmarek**
fixes #225

I'll fix `numerator(::Polymake.Rational)` here as well

### CODE REVIEW

File: src/integers.jl [hunk 1]
```diff
@@ -30,7 +30,10 @@ Base.promote_rule(::Type{<:Integer}, ::Type{<:AbstractFloat}) = Float64
 
 # BigInt constructor from Integer
 @inline function Base.BigInt(int::pmI) where pmI<:Integer
-    return deepcopy(unsafe_load(reinterpret(Ptr{BigInt},int.cpp_object)))
+    GC.@preserve int begin
+        i = deepcopy(unsafe_load(reinterpret(Ptr{BigInt},int.cpp_object)))
```
[the remark this answers is not in the document]
Comment (kalmarek) [reply src/integers.jl:34]: I did but I was wrong :D 
`unsafe_load` copies the memory, but `BigInt` contains a pointer, so pointer is copied, but not the underlying data. `deepcopy(::BigInt)` calls `MPZ.set` below which creates a new, completely independent `BigInt`; see my coment below

File: test/integers.jl [hunk 2]
```diff
@@ -88,4 +88,22 @@
         @test Polymake.Integer(1) << 2 == 4
         @test Polymake.Integer(4) >> 2 == 1
     end
+
+    @testset "weird BigInt issue" begin
+        test_f(n) = (k = Polymake.Integer(n); BigInt(k))
+        bn = test_f(5)
+        GC.gc();
+        @test bn == 5
```
Comment (kalmarek) [inline test/integers.jl:96]: this guards against invalid pointer in BigInt:
without `deepcopy` in the definition of `BigInt(::Polymake.Integer)` `bn` shares the underlying data with `k` and after `GC.gc()` that data is gone, so `bn` contains invalid pointer and is no longer equal to what it was.

Comment (saschatimme) [reply test/integers.jl:96]: i see
