### PR TITLE
fix/adjust signal handling

### LINKED ISSUE #233: signal handler
We set the signal handler for polymake.jl in `initialize_polymake` but this breaks Ctrl+C in julia afterwards.
Either we remove this or we need to set and unset this around every computation, and make sure we reset it to he correct one.

```
julia> sleep(5);
^CERROR: InterruptException:
Stacktrace:
 [1] poptaskref(::Base.InvasiveLinkedListSynchronized{Task}) at ./task.jl:564
 [2] wait() at ./task.jl:591
 [3] wait(::Base.GenericCondition{Base.Threads.SpinLock}) at ./condition.jl:104
 [4] stream_wait(::Timer, ::Base.GenericCondition{Base.Threads.SpinLock}) at ./stream.jl:47
 [5] wait(::Timer) at ./asyncevent.jl:116
 [6] sleep(::Int64) at ./asyncevent.jl:188
 [7] top-level scope at REPL[1]:1

julia> using Polymake
polymake version 4.0
Copyright (c) 1997-2020
Ewgenij Gawrilow, Michael Joswig, and the polymake team
Technische Universität Berlin, Germany
https://polymake.org
...

julia> sleep(5);
^C^C^C  (nothing happens)
julia> 
```

After removing the set_interrupt_signal from the polymake init Ctrl+C aborts julia and returns to the shell:

```
julia> using Polymake
polymake version 4.0
...

julia> sleep(5)
^C
lorenz $
```

It seems perl is also messing with the signal handler.

### PR DESCRIPTION
**Pull request by benlorenz**
This contains:
- [x] dont capture sigint from polymake (as it completely blocks it for julia)
- [x] use different signal for initalization of polymake Main.pm (otherwise julia terminates instantly on ctrl+c)
- [x] warn on ctrl+c during polymake computation

Fixes #233

Further ideas:
- [ ] Maybe we could add a similar warning for `polymake_call_function`.
- [ ] We should get julia to not interrupt polymake but that doesn't seem feasible at the moment.

Currently behaves like this, including the segfault during exit (when Ctrl+C was used to abort polymake at some point):
```julia
julia> using Polymake
polymake version 4.0
Copyright (c) 1997-2020
Ewgenij Gawrilow, Michael Joswig, and the polymake team
Technische Universität Berlin, Germany
https://polymake.org

This is free software licensed under GPL; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


julia> s = polytope.rand_sphere(15, 1000);

julia> s.VERTICES
^C┌ Warning: Interrupting polymake is not safe.
│ You are entering the dark forest of memory corruption in the valley segfaults, bring your 🏹, ⚔︎ and 🛡︎.
│ Please restart your julia session if you encounter any weird stuff.
└ @ Polymake ~/software/polymake/julia/Polymake-glibcxx.jl/src/perlobj.jl:45
ERROR: InterruptException:
Stacktrace:
 [1] internal_give(::Polymake.BigObjectAllocated, ::String) at /home/lorenz/.julia/packages/CxxWrap/LfTHV/src/CxxWrap.jl:597
 [2] give(::Polymake.BigObjectAllocated, ::String) at /home/lorenz/software/polymake/julia/Polymake-glibcxx.jl/src/perlobj.jl:41
 [3] getproperty(::Polymake.BigObjectAllocated, ::Symbol) at /home/lorenz/software/polymake/julia/Polymake-glibcxx.jl/src/perlobj.jl:58

julia> exit()

signal (11): Segmentation fault
in expression starting at REPL[5]:0
Segmentation fault
```

### CODE REVIEW

File: src/perlobj.jl [hunk 1]
```diff
@@ -41,6 +41,11 @@ function give(obj::BigObject, prop::String)
         internal_give(obj, prop)
     catch ex
         ex isa ErrorException && throw(PolymakeError(ex.msg))
+        if (ex isa InterruptException)
+            @warn("""Interrupting polymake is not safe.
+                   You are entering the dark forest of memory corruption in the valley segfaults, bring your 🏹, ⚔︎ and 🛡︎.
```
Comment (benlorenz) [inline src/perlobj.jl:46]:
```suggestion
                   You are entering the dark forest of memory corruption in the valley of segfaults, bring your 🏹, ⚔︎ and 🛡︎.
```

**Comment by benlorenz** [comment]
Unfortunately my terminal (urxvt) doesn't show them, I guess it is time to switch now.
Needed to fix a typo, can you approve once more please.

**Comment by kalmarek** [comment]
isn't this more a problem of the font?

maybe this suits your needs? https://github.com/Swordfish90/cool-retro-term :D
